import { Theme, ButtonStyleProps, ButtonSizeProps, ButtonVariant, ButtonState, ButtonSize } from "@ui/theme.slint";
import { Router } from "gen/router.slint";
import { Cj } from "cj.slint";

export { Theme, ButtonStyleProps, ButtonSizeProps, ButtonVariant, ButtonState, ButtonSize, Cj }
export * from "gen/exports.slint";

export component AppWindow inherits Window {
    title: "Coinjoin Signer";
    preferred-width: 480px;
    preferred-height: 800px;
    background: Theme.palette-background;

    Router { }
}
